# Local development override file
# Use this for local development: docker-compose -f docker-compose.yml -f docker-compose.local.yml up

services:
  web:
    build:
      context: ./app  # Relative path for local development
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DEBUG=True
      - SECRET_KEY=django-insecure-your-secret-key-here-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0 