services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins:/home/jenkins
      # Mount the host project into Jenkins container workspace:
      - /home/con-mac/dev/projects/ci-cd-django:/var/jenkins_home/workspace/ci-cd-django-pipeline
    environment:
      - JENKINS_ADMIN_ID
      - JENKINS_ADMIN_PASSWORD
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: ./app  # Relative path within Jenkins workspace
      dockerfile: Dockerfile
    container_name: django-web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DEBUG=True
      - SECRET_KEY=django-insecure-your-secret-key-here-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      - db

volumes:
  jenkins_home:
  pgdata:
