services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: django-web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app   # mount ./app correctly
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: