services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DEBUG=True
      - SECRET_KEY=django-insecure-your-secret-key-here-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  dependencytrack:
    image: dependencytrack/apiserver
    ports:
      - "8081:8080"
    environment:
      - ALPINE_DATABASE_MODE=internal
    volumes:
      - dependencytrack_data:/data  

  dependencytrack-frontend:
    image: dependencytrack/frontend
    ports:
      - "8082:8080"
    environment:
      - API_BASE_URL=http://localhost:8081
    depends_on:
      - dependencytrack

volumes:
  pgdata:
  sonarqube_data:
  sonarqube_extensions:
  dependencytrack_data:
